version: '3.8'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
      - ./app:/app/app
      - ./pipeline:/app/pipeline
      - ./evaluation:/app/evaluation
      - ./configs:/app/configs
      - ./scripts:/app/scripts
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
